version: '3.8'
services:
  backend:
    build: .
    command: npm run start:prod
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      JWT_SECRET: aK2sQz1P8RaT0HZmR4gG
      DATABASE_URL: postgresql://postgres.azwawdriroojtwkbofru:FintechPrueba123@aws-0-us-east-1.pooler.supabase.com:6543/postgres
    volumes:
      - .:/app